### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by mrhoads** [Azure-Samples/ms-identity-python-webapp#16] opened 2020-02-12 22:36 UTC
I followed the steps in the tutorial; however, when attempting to run `python app.py` or `flask run --port 5000`I received:

    Traceback (most recent call last):
    File "app.py", line 11, in <module>
    Session(app)
      File "/home/mrhoads/development/ms-identity-python-webapp/venv/lib/python3.7/site-packages/flask_session/__init__.py", line 54, in __init__
    self.init_app(app)
      File "/home/mrhoads/development/ms-identity-python-webapp/venv/lib/python3.7/site-packages/flask_session/__init__.py", line 61, in init_app
    app.session_interface = self._get_interface(app)
      File "/home/mrhoads/development/ms-identity-python-webapp/venv/lib/python3.7/site-packages/flask_session/__init__.py", line 93, in _get_interface
    config['SESSION_USE_SIGNER'], config['SESSION_PERMANENT'])
      File "/home/mrhoads/development/ms-identity-python-webapp/venv/lib/python3.7/site-packages/flask_session/sessions.py", line 313, in __init__
    from werkzeug.contrib.cache import FileSystemCache
    ModuleNotFoundError: No module named 'werkzeug.contrib'

I seemed to work around it by running `pip3 uninstall Werkzeug` followed by `pip3 install Werkzeug==0.16.0`.  That gets the app to run, though I don't know specifically why.  I wanted to capture it in an issue and the workaround for others who might encounter this.

**Comment by rayluo** [comment] 2020-02-13 00:32
The first search result of that error message `ModuleNotFoundError: No module named 'werkzeug.contrib'` leads me to [this post](https://www.reddit.com/r/cs50/comments/f0z3m5/cs50_web_project_1_modulenotfounderror_no_module/) created just 4 days ago. There are some discussion there too, speculating Flask issue or environment issue.

@mrhoads What version of [these packages](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/requirements.txt) are you using?

CC @navyasric, @abhidnya13: Perhaps we can try and see if we can reproduce this in a clean environment. @abhidnya13 did you observe same issue during our tests in recent days? If not, there would be not much we can do here.

**Comment by mrhoads** [comment] 2020-02-13 11:19
In a new virtualenv installing the requirements.txt I see:
|Package    |   Version   |
|-------------| ---------- |
|certifi       | 2019.11.28 |
| cffi         | 1.14.0   | 
chardet     |  3.0.4     |
Click       |  7.0       |
cryptography | 2.8       |
Flask        | 1.1.1     |
Flask-Session | 0.3.1     |
idna        |  2.8       |
itsdangerous | 1.1.0     |
Jinja2       | 2.11.1    |
MarkupSafe   | 1.1.1     |
msal         | 1.1.0     |
pip          | 20.0.2    |
pycparser    | 2.19      |
PyJWT        | 1.7.1     |
requests     | 2.22.0    |
setuptools   | 45.2.0    |
six          | 1.14.0    |
urllib3      | 1.25.8    |
Werkzeug     | 1.0.0     |
wheel       |  0.34.2  |

**Comment by daemonblade** [comment] 2020-02-13 22:30
Werkzeug 1.0.0 has removed deprecated code from 'werkzeug.contrib'. You can downgrade to Werkzeug 0.16.0 to work around this issue.

**Comment by rayluo** [comment] 2020-02-14 02:41
Thanks @daemonblade for the info! So this issue should be reported to our dependency, `flask_session`, and, it happens to already have a [duplicated issue there](https://github.com/fengsp/flask-session/issues/112). Ideally this should also be fixed from there. We will close this issue here, soon.

**Comment by JohannesSchwegler** [comment] 2020-02-14 08:16
@daemonblade downgrade works, thank 👍

**Comment by Frost199** [comment] 2020-02-14 09:02
I ran into the same issue when trying to use Proxyfix in `werkzeug==1.0.0` 

After downgrading to `werkzeug==0.16.0`, I got these warnings:
- > DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'.
This import is deprecated as of version 0.15 and will be removed in 1.0.

- >DeprecationWarning: 'werkzeug.contrib.cache' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to [pallets](https://github.com/pallets/cachelib).
from werkzeug.contrib.cache import FileSystemCache

To fix the issues:

- `pip install werkzeug==1.0.0`

For ProxyFix:
- `from werkzeug.middleware.proxy_fix import ProxyFix`

For FileSystemCache, you will have to install pallets:
- `pip install -U cachelib`
- `from cachelib.file import FileSystemCache`

I hope this helps and fix your issues 😄

**Comment by Great-Li-Xin** [comment] 2020-02-15 16:38
@Frost199 Dude, you are a life saver!

**Comment by donnguyen281** [comment] 2020-02-17 22:34
I am new to Linux and all the command lines that comes with it but am willing to learn!! Can you tell me what I am doing wrong here:

 health@T3500:~/gnuhealth/tryton/server/trytond-5.0.18/bin $ python3 ./trytond-admin --all --database=health01
Traceback (most recent call last):
  File "./trytond-admin", line 21, in <module>
    admin.run(options)
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/admin.py", line 54, in run
    activatedeps=options.activatedeps)
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/pool.py", line 149, in init
    self.start()
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/pool.py", line 102, in start
    register_classes()
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/modules/__init__.py", line 318, in register_classes
    import trytond.res
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/res/__init__.py", line 8, in <module>
    from . import routes
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/res/routes.py", line 10, in <module>
    from trytond.wsgi import app
  File "/home/health/gnuhealth/tryton/server/trytond-5.0.18/trytond/wsgi.py", line 12, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.contrib'

**Comment by rayluo** [comment] 2020-02-18 19:53
Thanks @Frost199 for the hint! With such root cause identified, we believe [this issue in upstream repo](https://github.com/fengsp/flask-session/issues/112) will probably be fixed by [this PR there](https://github.com/fengsp/flask-session/pull/114).

**Comment by willeswa** [comment] 2020-02-19 00:28
Just in case someone comes around before the fix PR is merged, downgrade to version 0.6.1

**Comment by donnguyen281** [comment] 2020-02-19 22:14
I tried removing werkzeug version 1.0,.0 and installed werkzeug version 0.16.0 
Typed in command ./trytond-admin --all --database=health01 = No output of what's going on and did not give me the option to add a password, Doing something in the background and just ended.... 

I will try to downgrade to version 0.6.1 and will let you guys know. Newbie to LINUX and Programming. THANK YOU FOR YOUR HELP!!!!!!!! 

Thanks guys!!!!

**Comment by ZayRTun** [comment] 2020-03-19 05:16
I am having this issue too.

  File "/home/zay/Python/tasks/venv/lib/python3.6/site-packages/Flask_Session-0.3.1-py3.6.egg/flask_session/sessions.py", line 313, in __init__
    from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'  

**pip list below**
click (7.1.1)
Flask (1.1.1)
Flask-Session (0.3.1)
itsdangerous (1.1.0)
Jinja2 (2.11.1)
MarkupSafe (1.1.1)
pip (9.0.1)
pkg-resources (0.0.0)
setuptools (39.0.1)
Werkzeug (1.0.0)

**Comment by Alshafei2430** [comment] 2020-03-20 05:54
> I ran into the same issue when trying to use Proxyfix in `werkzeug==1.0.0`
> 
> After downgrading to `werkzeug==0.16.0`, I got these warnings:
> 
> * > DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'.
>   > This import is deprecated as of version 0.15 and will be removed in 1.0.
> * > DeprecationWarning: 'werkzeug.contrib.cache' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to [pallets](https://github.com/pallets/cachelib).
>   > from werkzeug.contrib.cache import FileSystemCache
> 
> To fix the issues:
> 
> * `pip install werkzeug==1.0.0`
> 
> For ProxyFix:
> 
> * `from werkzeug.middleware.proxy_fix import ProxyFix`
> 
> For FileSystemCache, you will have to install pallets:
> 
> * `pip install -U cachelib`
> * `from cachelib.file import FileSystemCache`
> 
> I hope this helps and fix your issues 😄

Thank you, this solution worked for me .
I was struggling in that problem all for two days, thank you again.

**Comment by rayluo** [comment] 2020-03-27 00:03
@Frost199 , would you mind contact me and share how exactly you workaround this?

In particular, how did you use that `from cachelib.file import FileSystemCache`? Did you have to patch that `flask_session` too?

**Comment by Alshafei2430** [comment] 2020-03-27 00:29
After installing cachelib 
go to site-packages and change the session.py file   
change "from werkzeug.contrib.cache import FileSystemCache" in line 313  to
"from cachelib.file import FileSystemCache"
![image](https://user-images.githubusercontent.com/52571066/77708868-f5beed80-6fd1-11ea-8b27-01423ee9d5e3.png)

**Comment by filak** [comment] 2020-04-02 15:03
@Alshafei2430 Thanks for the tip, but it did not work for me - the cachlib seems to be different...  

I use Flask-Caching so I have used this import instead:

`from flask_caching.backends.filesystem import FileSystemCache`

**Comment by rayluo** [comment] 2020-04-02 16:37
Hi @filak , I also followed @Alshafei2430 's hint, and it worked, at least on my computer<sup>TM</sup>. :-)

Would you mind following step 2 of [this pending PR](https://github.com/Azure-Samples/ms-identity-python-webapp/pull/21) to see if that workaround would work for you too? It would be helpful to have more people testing it, before we merge it in.

**Comment by filak** [comment] 2020-04-02 17:57
@rayluo I do not have the Azure tenant and it seems a bit complicated...

The cachelib FileSystemCache do not play well with Flask-session - it keeps resetting the session so I was not able to login. When using the module from flask_caching everything works as before.

**Comment by abhidnya13** [comment] 2020-04-02 18:30
@rayluo Same happens when I test it too as @filak

**Closed** 2020-04-03 00:31 UTC
Labels: duplicate, question

**Comment by madsjordt** [comment] 2020-04-08 09:53
Hi guys, 
when executing "flask run" I receive the following error message:
Error: While importing "application", an ImportError was raised:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/ubuntu/pset8/finance/application.py", line 9, in <module>
    from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'

I tried the hints provided in this thread but it just won't work. Quite sure I am doing something wrong but I just don't know what.
Hope one of you guys can help me!

**Comment by Frost199** [comment] 2020-04-08 14:39
a lot can contribute to this, can you share your requirements.txt so we know the libraries that are dependent on werkzeug, it might be flask uploads, it might be something else, so we can not tell where the problem is from if this is all the information you are giving.

**Comment by madsjordt** [comment] 2020-04-08 14:55
Of course @Frost199, totally right.
Please find requirements.txt content attached.

![Bildschirmfoto 2020-04-08 um 16 53 47](https://user-images.githubusercontent.com/56762020/78798822-b6bd6e80-79b9-11ea-9efd-2d74c6478694.png)
![Bildschirmfoto 2020-04-08 um 16 53 41](https://user-images.githubusercontent.com/56762020/78798832-b8873200-79b9-11ea-84a2-b77d5d55a90d.png)
![Bildschirmfoto 2020-04-08 um 16 53 30](https://user-images.githubusercontent.com/56762020/78798833-b91fc880-79b9-11ea-86d7-46dce3a7d3d6.png)

**Comment by Frost199** [comment] 2020-04-08 15:23
from your attachment, you are using werkzeug==0.16.0, you shouldn't have such issues using with werkzeug.contrib as the first issue made by @mrhoads  on this thread was fixed downgrading to 0.16.0, you might be doing something wrong and this error is only thrown if you are using werkzeug>=1.0

here is a screenshot from werkzeug changelog 1.0.x
![Screenshot 2020-04-08 at 16 20 16](https://user-images.githubusercontent.com/25561713/78801702-eb7af700-79b4-11ea-9b86-39eda56f23c2.png)


or check out the link [werkzeug changelog 1.0.x](https://werkzeug.palletsprojects.com/en/1.0.x/changes/)

**Comment by gottigjavier** [comment] 2020-04-23 01:01
First (pip or pip3):
$ pip3 install werkzeug==1.0.0
$ pip3 install -U cachelib

Then, you need change in flask_session/sessions.py, around line 311:
from werkzeug.contrib.cache import FileSystemCache
for:
from cachelib import FileSystemCache

**Comment by rayluo** [comment] 2020-04-23 04:20
@gottigjavier I've fixed this via #21.

* If you download/clone this sample now and start afresh, it should work out of box.
* If you are using an older version of this sample, or if you are working on your own project, you can follow [this description](https://github.com/Azure-Samples/ms-identity-python-webapp/pull/21#issue-395038340) to patch your environment, by:

  ```
  pip uninstall flask-session
  git+https://github.com/rayluo/flask-session@0.3.x#egg=flask-session
  ```
* If you want to avoid such inconvenient manual workaround, please help upvote [my petition here](https://github.com/pypa/pypi-support/issues/318) to help me take over the maintenance of that now-abandoned flask-session project.

**Comment by LoveDuckie** [comment] 2020-04-29 19:00
Hey everyone. 

I found that the easiest way of dealing with this problem is by simply copying the contents of the `FileSystemSessionInterface`, making a new version inside of your own project, and changing `from werkzeug.contrib.cache import FileSystemCache` to .

I don't agree with the approach of modifying the contents of a package once it has been installed with `pip install`. The reason being is that if you are deploying your Flask application to a platform such as Google App Engine, you won't be able to inject the aforementioned modifications once the runtime has installed all of your [service's dependencies from the requirements.txt file.](https://cloud.google.com/appengine/docs/standard/python3/specifying-dependencies)

Hopefully someone takes over this project or fixes the problem soon, but in the mean time, I found that was the best method for fixing this (if you're reliant on the filesystem implementation)!

Many thanks to @Frost199 for identifying where the missing reference now exists. :)

**Comment by rayluo** [comment] 2020-04-29 20:00
Hi @LoveDuckie , isn't [this](https://github.com/Azure-Samples/ms-identity-python-webapp/issues/16#issuecomment-618168231) even easier?

```
pip uninstall flask-session
git+https://github.com/rayluo/flask-session@0.3.x#egg=flask-session
```

Specifically, it does not "modifying the contents of a package once it has been installed with `pip install`". It just installs a workable version, technically still via `pip install`.

**Comment by LoveDuckie** [comment] 2020-04-29 20:39
@rayluo is git+https://github.com/rayluo/flask-session@0.3.x#egg=flask-session definable as a dependency under a generated `requirements.txt`?

For example, can that be placed under all the other listings in a `requirements.txt` file?

**Comment by rayluo** [comment] 2020-04-29 20:47
@LoveDuckie , you mean, [like this](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/requirements.txt#L3)? :-)

**Comment by LoveDuckie** [comment] 2020-04-29 21:34
> @LoveDuckie , you mean, [like this](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/requirements.txt#L3)? :-)

Struggling to understand why a particular GitHub fork URL has to be referenced in a requirements.txt file instead of publishing it to the PyPI package repository. I really don't mean any offence, but I have no interest in hooking up a random GitHub fork to a production application via it's associated requirements.txt file. If you are a contributor (as you've been tagged as), then I don't see why the [official PyPI package](https://pypi.org/) can't be updated. I appreciate your efforts all the same.

Between writing my own session interface implementation and having complete control over it, and using a GitHub user's fork as the solution for a service in a production environment -- I think I know which I'd prefer.

**Comment by rayluo** [comment] 2020-04-29 23:40
@LoveDuckie , you may not realize this. There are actually 2 different packages here:

* A web app sample in this repo, which has a dependency on:
* A `flask-session` package hosted in PyPI.

I'm one of the contributor of this web app sample, but I do NOT own that `flask-session`. The best I can do, for now, is to provide a fix, hosted in my fork repo, and then [have this web app sample to "use a github user's fork"](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/requirements.txt#L3) - and that user happens to be me.

Feel free to make an educated decision on choosing whatever path you prefer.

**Comment by LoveDuckie** [comment] 2020-04-30 01:58
I misunderstood that this issue was being raised on a completely unrelated sample code repository that you are a contributor of, and *not* the `flask-session` repository. Regardless of good intentions I don't think it's a good idea to use someone else's GitHub fork as a dependency on a production service. 

Good luck with taking over `flask-session`. Thanks again for your efforts.

**Comment by ednasawe** [comment] 2020-05-06 23:26
Thank you, downgrading to Werkzeug 0.16.0 from 1.0.0 worked!

**Comment by b-hintz** [comment] 2020-05-13 00:53
Thank you so much for providing this answer! I was tearing my hair out over this issue!

**Comment by Divide-By-0** [comment] 2020-07-21 05:17
In case anyone else is having this error, I changed
```from werkzeug.contrib.profiler import ProfilerMiddleware```
to
```from werkzeug.middleware.profiler import ProfilerMiddleware```

**Comment by rayluo** [comment] 2020-07-21 19:38
@Divide-By-0 , I suspect that you were brought to this thread by search engine based on keywords. But this issue and this repo are for a Web App sample for Microsoft identity platform, and [we've fixed that issue in our sample 4 months ago](https://github.com/Azure-Samples/ms-identity-python-webapp/blame/master/app.py#L17).

I'll probably lock this conversation thread, to avoid future confusion on both sides.
