### ISSUE TITLE
Edit Profile Not Working for B2C After Login

### ISSUE THREAD

**Issue by bwhybel** [Azure-Samples/ms-identity-python-webapp#126] opened 2024-01-23 05:03 UTC
I have been following the instructions for B2C [here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-python-web-app?tabs=macos). There are a few instances where the instructions are not super clear, but have been able to parse through them nonetheless. However, I'm stuck on utilizing the `Edit Profile` link on the home page after logging in. I keep seeing this error: 
```
ValueError

ValueError: The web page with complete_log_in() MUST be visited after the web page with log_in()
```

I'm not sure what the issue is here. Should this:
```
@app.route(app_config_b2c.REDIRECT_PATH)
def auth_response():
    result = auth.complete_log_in(request.args)
    if "error" in result:
        return render_template("auth_error.html", result=result)
    return redirect(url_for("index"))
``` 
actually not be the function definition for the auth response?

**Comment by rayluo** [comment] 2024-01-23 05:20
Nah. You shouldn't need to change [that route](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/app.py#L40) (or anything inside `app.py` for that matter). The same source code is expected to support B2C, as long as you configured your B2C settings into your `.env` like [this](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/.env.sample). Does that not work for you?

**Comment by bwhybel** [comment] 2024-01-23 05:23
Didn't I have to change [this](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/app.py#L6) to pull `app_config_b2c` (and then all the additional calls)?

**Comment by bwhybel** [comment] 2024-01-23 05:26
Is it possible my edit profile user flow is incorrectly setup? Didn't seem like there were any requirements when setting it up, but even when i run that user flow from the azure portal, I'm getting that error page

**Comment by rayluo** [comment] 2024-01-23 05:28
> Didn't I have to change [this](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/app.py#L6) to pull `app_config_b2c` (and then all the additional calls)?

Sorry for the confusion. You should follow our README, particularly [this section](https://github.com/Azure-Samples/ms-identity-python-webapp#if-you-are-configuring-your-b2c-app). (FWIW, the external docs that it links to, was also recently updated, specifically for this sample. So, the sample and its doc are in sync and up-to-date.) Let us know how that goes.

BTW, the existing `app_config_b2c.py` was a relic. We will remove it in our next commit.

**Comment by bwhybel** [comment] 2024-01-23 05:31
Going back to that gives me: 
![image](https://github.com/Azure-Samples/ms-identity-python-webapp/assets/18406268/c6de507b-00b3-422a-8b9d-cf495fc9f49e)
when I try to login. I don't see setting up that scope anywhere in the README or the documentation.

**Comment by rayluo** [comment] 2024-01-23 05:34
> Going back to that gives me: ![image](https://private-user-images.githubusercontent.com/18406268/298815069-c6de507b-00b3-422a-8b9d-cf495fc9f49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODgxOTcsIm5iZiI6MTcwNTk4Nzg5NywicGF0aCI6Ii8xODQwNjI2OC8yOTg4MTUwNjktYzZkZTUwN2ItMDBiMy00MjJhLThiOWQtY2Y0OTVmYzlmNDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA1MzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmQxYjlhM2YxZTU0YTZiNjk1MWUwYzVjMzA3Yjk0NDQyZmViYWI3OTIxNzkyY2U4MWZkNzg1MDg2ZDQ3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jYwiVAZljJ5Z3xrQEG6hKAkwqTEFYB6vG0HQ2VjX9AE) when I try to login. I don't see setting up that scope anywhere in the README or the documentation.

The README and/or the doc just tell you what steps would be needed to setup your app, such as what settings are needed. But you are the only one who would know the actual values that is suitable to your setup, such as what API your app is going to call, what scope that API would require.

Does that make sense?

**Comment by bwhybel** [comment] 2024-01-23 05:35
I guess I'm confused why all the information about the `SCOPE` parameter would be included in step 6, but I'm getting this failure on step 5.

**Comment by rayluo** [comment] 2024-01-23 05:37
> I guess I'm confused why all the information about the `SCOPE` parameter would be included in step 6, but I'm getting this failure on step 5.

Fair point. We will keep this in mind and improve this part in a future commit.

**Comment by bwhybel** [comment] 2024-01-23 05:42
Am I correct that I do need to delete [the value from this array](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/app_config.py#L41) in order to get a working solution?

**Comment by bwhybel** [comment] 2024-01-23 05:44
Or are there additional steps i need to do in the B2C tenant for it to work with `User.ReadBasic.All`?

**Comment by rayluo** [comment] 2024-01-23 05:46
> Am I correct that I do need to delete [the value from this array](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/app_config.py#L41) in order to get a working solution for part 5?

IIRC, that should work.



> Or are there additional steps i need to do in the B2C tenant for it to work with `User.ReadBasic.All`?

The scope `User.ReadBasic.All` is for Microsoft Graph. I believe B2C does not access MS Graph. You can keep the scopes empty so that your app will do sign-in only. You will do the "call an API" part later when you have your own API in your B2C tenant at that time.

**Comment by bwhybel** [comment] 2024-01-23 05:48
thanks, i'm coming into this totally cold, so things not working when I think I'm following the docs gets confusing

**Comment by bwhybel** [comment] 2024-01-23 05:49
I'm still not able to get my edit_profile flow to work though

**Comment by bwhybel** [comment] 2024-01-23 06:00
should the redirect after editing profile really be calling into 
```
    result = auth.complete_log_in(request.args)
```
?

It seems like that needs to directly follow a call `log_in`, but is an edit profile flow going to do that? Because that is just going to this link: https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/templates/index.html#L17

**Comment by rayluo** [comment] 2024-01-23 06:17
Quick question. When that "unable to get my edit_profile flow to work" happens, have you already successfully logged in, and even successfully visited the Edit Profile page? In other words, did the issue only happen when you are returning from the Edit Profile page?

I do not currently have a set of B2C setup for me to reproduce this. If you are interested in sharing a set of test setup to my email (visible in my github profile), I can take a close look in the next several days.

**Comment by bwhybel** [comment] 2024-01-23 15:10
Sorry, yes that's unclear. The edit profile flow is working (I get to the generic "edit user details page), but as soon as I click `continue` on that page, it redirects to me to `localhost:5000/getAToken` and fails

**Comment by rayluo** [comment] 2024-01-23 23:02
UPDATE: Since I do not currently have a B2C setup to reproduce the issue, I'm providing this tentative adjustment for you to test, @bwhybel 

Run the following command in your environment, and let me know whether that helps.

`pip install git+https://github.com/rayluo/identity.git@fallback`

**Comment by bwhybel** [comment] 2024-01-24 01:16
so that does work now, I'm just getting this error now:

We found no prior log_in() info from current session. This situation may be caused by: (1) Special scenarios such as returning from B2C's edit profile, in which case you can simply ignore this warning, or (2) sessions were all reset due to a recent server restart, in which case you can simply restart a new log-in, or (3) the session was stored on the file system of another server, in which case you need to use either a centralized session store or a load balancer with sticky session (a.k.a. affinity cookie).

**Comment by rayluo** [comment] 2024-01-24 02:13
> so that does work now,

Great. Then the fix works. I'll merge that in and cut a new release in the near future.

> I'm just getting this message* now:
> 
> We found ... may be caused by: (1) Special scenarios such as returning from B2C's edit profile, in which case you can simply ignore this warning, ...
> 
> so what did that package actually change without making any changes to code?

If you meant to say "without making any changes to (this sample's) code", then it should not come as a surprise. The sample itself contains very few source code, because most of the heavy-lifting is done by underlying libraries. In this case, an oversensitive hard failure (exception) is now changed to an informative warning. That makes the difference.

**Comment by rayluo** [comment] 2024-01-28 02:53
Now [fixed in upstream library](https://github.com/rayluo/identity/releases/tag/0.3.3).

**Closed by rayluo** 2024-01-28 02:53 UTC
Labels: question
